"""created address

Revision ID: 59287f0e6490
Revises: f35b64c21a68
Create Date: 2023-01-12 18:35:36.562515

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59287f0e6490'
down_revision = 'f35b64c21a68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=200), nullable=False))
        batch_op.drop_column('full_address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_address', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('address')

    # ### end Alembic commands ###
