"""updated address table

Revision ID: 710e49da8613
Revises: 45fdb75a9160
Create Date: 2023-01-12 11:29:18.444213

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '710e49da8613'
down_revision = '45fdb75a9160'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('street_address', sa.String(length=100), nullable=False))
        batch_op.add_column(sa.Column('city', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('state', sa.String(length=20), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key("address_user_fk", 'user', ['user_id'], ['id'])
        batch_op.drop_column('address')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.VARCHAR(length=200), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('user_id')
        batch_op.drop_column('zip_code')
        batch_op.drop_column('state')
        batch_op.drop_column('city')
        batch_op.drop_column('street_address')

    # ### end Alembic commands ###
