"""updated address table

Revision ID: f35b64c21a68
Revises: 710e49da8613
Create Date: 2023-01-12 11:35:45.856406

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f35b64c21a68'
down_revision = '710e49da8613'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_address', sa.String(length=200), nullable=False))
        batch_op.drop_column('zip_code')
        batch_op.drop_column('street_address')
        batch_op.drop_column('state')
        batch_op.drop_column('city')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('address', schema=None) as batch_op:
        batch_op.add_column(sa.Column('city', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('state', sa.VARCHAR(length=20), nullable=False))
        batch_op.add_column(sa.Column('street_address', sa.VARCHAR(length=100), nullable=False))
        batch_op.add_column(sa.Column('zip_code', sa.VARCHAR(length=10), nullable=False))
        batch_op.drop_column('full_address')

    # ### end Alembic commands ###
